language: cpp

compiler:
    - gcc
#    - clang

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo add-apt-repository --yes ppa:kalakris/cmake

    # g++4.8.1
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

    # clang 3.4
    - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
    - sudo apt-get update -qq

install:
    # g++4.8.1
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

    # clang 3.4
    - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
    - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

    - sudo apt-get install qtbase5-dev qt5-default qttools5-dev-tools cmake

before_script:
    - git clone https://github.com/Itseez/opencv.git
    - git clone https://github.com/Itseez/opencv_contrib
    - cd opencv
    - mkdir build
    - cd build
    - cmake -DBUILD_EXAMPLES=OFF \\
            -DBUILD_TESTS=OFF \\
            -DBUILD_PERF_TESTS=OFF \\
            -DBUILD_opencv_xphoto=OFF \\
            -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules ..
    - make -j5
    - sudo make install
    - cd ../..
    - mkdir build
    - cd build
    - cmake -DOpenCV_DIR=/usr/local/share/OpenCV ..

script: make -j5

notifications:
    email: false
